/*
 * Copyright 2017 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package curriculumcourse.curriculumcourse;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Course implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    private java.lang.String code;
    private Teacher teacher;
    private int lectureSize;
    private int minWorkingDaySize;
    private java.util.List<Curriculum> curriculumList;
    private int studentSize;

    private java.lang.Long id;

    public Course() {
    }

    public java.lang.String getCode() {
        return this.code;
    }

    public void setCode(java.lang.String code) {
        this.code = code;
    }

    public int getLectureSize() {
        return this.lectureSize;
    }

    public void setLectureSize(int lectureSize) {
        this.lectureSize = lectureSize;
    }

    public int getMinWorkingDaySize() {
        return this.minWorkingDaySize;
    }

    public void setMinWorkingDaySize(int minWorkingDaySize) {
        this.minWorkingDaySize = minWorkingDaySize;
    }

    public java.util.List<Curriculum> getCurriculumList() {
        return this.curriculumList;
    }

    public void setCurriculumList(
            java.util.List<Curriculum> curriculumList) {
        this.curriculumList = curriculumList;
    }

    public int getStudentSize() {
        return this.studentSize;
    }

    public void setStudentSize(int studentSize) {
        this.studentSize = studentSize;
    }

    public java.lang.Long getId() {
        return this.id;
    }

    public void setId(java.lang.Long id) {
        this.id = id;
    }

    public Teacher getTeacher() {
        return this.teacher;
    }

    public void setTeacher(Teacher teacher) {
        this.teacher = teacher;
    }

    public Course(java.lang.String code,
                  Teacher teacher,
                  int lectureSize,
                  int minWorkingDaySize,
                  java.util.List<Curriculum> curriculumList,
                  int studentSize,
                  java.lang.Long id) {
        this.code = code;
        this.teacher = teacher;
        this.lectureSize = lectureSize;
        this.minWorkingDaySize = minWorkingDaySize;
        this.curriculumList = curriculumList;
        this.studentSize = studentSize;
        this.id = id;
    }
}