/*
 * Copyright 2017 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package curriculumcourse.curriculumcourse;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.optaplanner.core.api.domain.entity.PlanningEntity
public class Lecture implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    private Course course;
    private int lectureIndexInCourse;
    private boolean locked;

    @org.optaplanner.core.api.domain.variable.PlanningVariable(valueRangeProviderRefs = {"periodRange"})
    private Period period;

    @org.optaplanner.core.api.domain.variable.PlanningVariable(valueRangeProviderRefs = {"roomRange"})
    private Room room;

    private java.lang.Long id;

    public Lecture() {
    }

    public Course getCourse() {
        return this.course;
    }

    public void setCourse(Course course) {
        this.course = course;
    }

    public int getLectureIndexInCourse() {
        return this.lectureIndexInCourse;
    }

    public void setLectureIndexInCourse(int lectureIndexInCourse) {
        this.lectureIndexInCourse = lectureIndexInCourse;
    }

    public boolean isLocked() {
        return this.locked;
    }

    public void setLocked(boolean locked) {
        this.locked = locked;
    }

    public Period getPeriod() {
        return this.period;
    }

    public void setPeriod(Period period) {
        this.period = period;
    }

    public Room getRoom() {
        return this.room;
    }

    public void setRoom(Room room) {
        this.room = room;
    }

    public java.lang.Long getId() {
        return this.id;
    }

    public void setId(java.lang.Long id) {
        this.id = id;
    }

    public Lecture(curriculumcourse.curriculumcourse.Course course,
                   int lectureIndexInCourse,
                   boolean locked,
                   curriculumcourse.curriculumcourse.Period period,
                   curriculumcourse.curriculumcourse.Room room,
                   java.lang.Long id) {
        this.course = course;
        this.lectureIndexInCourse = lectureIndexInCourse;
        this.locked = locked;
        this.period = period;
        this.room = room;
        this.id = id;
    }
}